#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x manifest-tool

# Generate the manifest file.

function generate_manifest {
  cat > manifest-generated.yaml << EOF
image: trixam/arm32v7-docker-adbhone:latest
manifests:
  - image: trixam/arm32v7-docker-adbhone:amd64
    platform:
      architecture: amd64
      os: linux
  - image: trixam/arm32v7-docker-adbhone:arm32v7
    platform:
      architecture: arm
      os: linux
      variant: v7
  - image: trixam/arm32v7-docker-adbhone:arm64v8
    platform:
      architecture: arm64
      os: linux
      variant: v8
EOF
}

echo "Pushing multi-arch manifest $IMAGE_NAME"
generate_manifest
env
#$IMAGE_NAME $IMAGE_NAME
./manifest-tool push from-spec manifest-generated.yaml
